# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/adhisatoe
  Twitter: https://twitter.com/adhisatoe

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '4fad829eae8fee00533a'
    # 应用秘钥
    clientSecret: '7d9bd44dab695097e47c4f19a7624b136e6dd90e'
    # issue仓库名
    repo: 'adhisatoe.github.io'
    # Github名
    owner: 'adhisatoe'
    # Github名
    admin: ['adhisatoe']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: AdhiDazz

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
